version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blockbrief"
s3_prefix = "blockbrief"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TelegramBotToken=\"\""
